### ISSUE TITLE
Redis?

### ISSUE THREAD

**Issue by faoziaziz** [umardx/image#1]
Kenapa orang seneng pake redis yah mar?

**Comment by umardx** [comment]
karena orang seneng 😄

**Comment by faoziaziz** [comment]
Mantap pisan euy Sent from Mail for Windows From: Umar NawawiSent: 04 November 2021 11:51To: umardx/imageCc: Aziz Amerul Faozi; AuthorSubject: Re: [umardx/image] Redis? (#1) karena orang seneng 😄—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
